# Taken from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
# For future reference and copyrights

# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t coyote-testing-ci .
      - docker tag coyote-testing-ci $DOCKER_USERNAME/coyote-testing-ci
      - docker push $DOCKER_USERNAME/coyote-testing-ci
